### ISSUE TITLE
Image URL Validation

### ISSUE THREAD

**Issue by AppFolioRopes** [AppFolioOnboarding/image-sharer-wangyuesong#4]
#### As a user I want to be prevented from submitting invalid image URLs.

Acceptance criteria:
- [x] I cannot successfully save an image with an invalid URL.
- [x] An error message is associated with the appropriate input field on
  failure.

Discussion Topic:
- [x] What is a valid image URL?

Dependencies:
- Save Image Link

**Comment by wangyuesong** [comment]
Invalid url: 'hahaha' 'https://google.com'

**Comment by wangyuesong** [comment]
Found a lot of stuff were wrong after the test class. So

https://github.com/AppFolioOnboarding/image-sharer-wangyuesong/commit/82758275bf02a086abc39c2212a838030896ee98

https://github.com/AppFolioOnboarding/image-sharer-wangyuesong/commit/f07047b31c1d1539e32c7e3b031c4fba7358220a

These two commits should close #4 and #5 together
